Quick astarte instance
astarte-platform/sdk-doc pull request #14
Opened 2024-11-28 15:58 UTC by sorru94

2024-11-29 10:08 UTC, rgallor requested changes

2024-11-29 11:17 UTC, lucaato requested changes

2024-11-29 11:17 UTC, lucaato commented on source/astarte_quick_instance.md
> +reliable storage and adequate redundancy beneath it.
Since we really want a "quick and dirty" guide I think this last section after "Astarte enterprise" is not needed. We already warned them enough and this does not add much to it.

2024-11-29 11:17 UTC, lucaato commented on source/get_started.md
> +If you are new to Astarte and would like to quicly test one of our SDKs with an Astarte instance
```suggestion
If you are new to Astarte and would like to quickly test one of our SDKs with an Astarte instance
```

2024-11-29 11:17 UTC, lucaato commented on source/get_started.md
> +with to dive deeper in the Astarte platform.
```suggestion
want to dive deeper in the Astarte platform's inner workings.
```

2024-12-02 11:56 UTC, harlem88 requested changes

2024-12-02 11:56 UTC, harlem88 commented on astarte-setup.sh
> +    git clone https://github.com/astarte-platform/astarte.git -b v1.2.0 "$ASTARTE_SETUP_CLONE_DIR"
What do you think moving Astarte version to a const variable, so that when updating the Astarte version, you only have a single point ?
```suggestion
    git clone https://github.com/astarte-platform/astarte.git -b $ASTARTE_VERSION "$ASTARTE_SETUP_CLONE_DIR"
```

2024-12-02 11:56 UTC, harlem88 commented on astarte-setup.sh
> +    docker run -v "$(pwd)/compose:/compose" astarte/docker-compose-initializer:1.2.0
same above
```suggestion
    docker run -v "$(pwd)/compose:/compose" astarte/docker-compose-initializer:$ASTARTE_VERSION
```

2024-12-02 13:21 UTC, harlem88 commented on astarte-setup.sh
> +    docker run -v "$(pwd)/compose:/compose" astarte/docker-compose-initializer:1.2.0
yep, but is it not follow the same version of Astarte?

2024-12-02 14:11 UTC, joshuachp requested changes

2024-12-02 14:11 UTC, joshuachp commented on astarte-setup.sh
> +ASTARTE_SETUP_COMPOSE_INIALIZER_VERSION="1.2.0"
I would separate and remove the prefix from those variables

2024-12-02 14:11 UTC, joshuachp commented on astarte-setup.sh
> +    mkdir "$ASTARTE_SETUP_CLONE_DIR"
```suggestion
    mkdir -p "$ASTARTE_SETUP_CLONE_DIR"
```

2024-12-02 14:57 UTC, harlem88 requested changes

2024-12-02 14:57 UTC, harlem88 commented on source/astarte_quick_instance.md
> +For the purpose of this demo we will use an external service `nip.io` which works as a wildcard DNS
What do you think to add a reference to `nip.io`? 
```suggestion
For the purpose of this demo we will use an external service [`nip.io`](https://nip.io/) which works as a wildcard DNS
```

2024-12-02 15:12 UTC, matt-mazzucato requested changes

2024-12-03 09:49 UTC, sorru94 commented on source/astarte_quick_instance.md
> +astartectl --astarte-url http://api.astarte.<YOUR IP ADDRESS>.nip.io housekeeping -k compose/astarte-keys/housekeeping_private.pem realms create --realm-public-key test_public.pem test -y
I think it's more readable if each flag is placed after its command.
For example, the `--astarte-url` is a generic option that is valid for any astartectl subcommand.

2024-12-03 09:52 UTC, sorru94 commented on source/astarte_quick_instance.md
> +astartectl utils gen-jwt all-realm-apis -k test_private.pem
I would make it never expiring to avoid confusion for the user.

2024-12-03 10:26 UTC, matt-mazzucato approved these changes

2024-12-03 13:30 UTC, lucaato approved these changes

2024-12-06 10:05 UTC, harlem88 approved these changes

2024-12-06 10:10 UTC, rgallor approved these changes

2024-12-06 11:37 UTC, joshuachp requested changes

2024-12-06 11:37 UTC, joshuachp commented on astarte-setup.sh
> +ASTARTE_SETUP_BASE_DOMAIN=${DOCKER_COMPOSE_ASTARTE_BASE_DOMAIN:-'astarte.localhost'}
```suggestion
if [[ -n $DOCKER_COMPOSE_ASTARTE_BASE_DOMAIN ]]; then
    ASTARTE_SETUP_BASE_DOMAIN="$DOCKER_COMPOSE_ASTARTE_BASE_DOMAIN"
else
    ASTARTE_SETUP_BASE_DOMAIN=${ASTARTE_SETUP_BASE_DOMAIN:-'astarte.localhost'}
fi
```

2024-12-06 11:37 UTC, joshuachp commented on astarte-setup.sh
> +ASTARTE_SETUP_BASE_DOMAIN=${DOCKER_COMPOSE_ASTARTE_BASE_DOMAIN:-'astarte.localhost'}
The environment variable ASTARTE_SETUP_BASE_DOMAIN is not overridable otherwise

2024-12-06 11:37 UTC, joshuachp commented on astarte-setup.sh
> +ASTARTE_SETUP_CLONE_DIR=${ASTARTE_SETUP_CLONE_DIR:-"$HOME"}
```suggestion
ASTARTE_SETUP_CLONE_DIR=${ASTARTE_SETUP_CLONE_DIR:-"$PWD"}
```

Shouldn't we prefer the current working directory?

2024-12-06 11:37 UTC, joshuachp commented on astarte-setup.sh
> +    echo "  --clone-dir   Directory where Astarte will be cloned (default: $ASTARTE_SETUP_CLONE_DIR)"
```suggestion
    echo "  --clone-dir   Directory where Astarte will be cloned into as 'astarte' (default: $ASTARTE_SETUP_CLONE_DIR)"
```

2024-12-06 11:37 UTC, joshuachp commented on astarte-setup.sh
> +    echo "  --clone-dir   Directory where Astarte will be cloned (default: $ASTARTE_SETUP_CLONE_DIR)"
It's just a nitpik, I think this would make it a bit clearer that will create a new directory called 'astarte'.

2024-12-06 11:37 UTC, joshuachp commented on astarte-setup.sh
> +    if find "$ASTARTE_SETUP_CLONE_DIR" -mindepth 1 -maxdepth 1 -print | wc -l | grep -q . ; then
I tried this command, but it doesn't check if the directory is empty

2024-12-06 11:37 UTC, joshuachp commented on astarte-setup.sh
> +    if find "$ASTARTE_SETUP_CLONE_DIR" -mindepth 1 -maxdepth 1 -print | wc -l | grep -q . ; then
```suggestion
    count=$(find "$ASTARTE_SETUP_CLONE_DIR" -mindepth 1 -maxdepth 1 | wc -l)
    if [[ $count -ne 0 ]]; then
```

2024-12-06 12:29 UTC, sorru94 commented on astarte-setup.sh
> +ASTARTE_SETUP_CLONE_DIR=${ASTARTE_SETUP_CLONE_DIR:-"$HOME"}
The home directory would make it less likely for some user to create multiple Astarte instances all in slightly different folders.

2024-12-06 13:40 UTC, joshuachp requested changes

2024-12-06 13:40 UTC, joshuachp commented on astarte-setup.sh
> +if [[ -n $DOCKER_COMPOSE_ASTARTE_BASE_DOMAIN ]]; then
```suggestion
if [[ -n ${DOCKER_COMPOSE_ASTARTE_BASE_DOMAIN:-} ]]; then
```

2024-12-06 13:40 UTC, joshuachp commented on astarte-setup.sh
> +if [[ -n $DOCKER_COMPOSE_ASTARTE_BASE_DOMAIN ]]; then
My bad, there was an error in my previous sudgestion

2024-12-06 14:53 UTC, joshuachp approved these changes

2024-12-06 14:59 UTC, harlem88 approved these changes

2024-12-06 14:59 UTC, merged